#GUI with tkinter
# import tkinter as tk
# #import tkinter
# #top=tkinter.Tk()
# top=tk.Tk()
# top.title("python")
# top.geometry("400x600")
# #top.configure(bg="teal")
# top.configure(bg="#008080")
# frame=tk.Frame(bg="#008080")
# login_label=tk.Label(frame,text="Login page",bg="#008080",fg="#ffffff",font=("arial",30),pady=10)
# username_label=tk.Label(frame,text="username",bg="#008080",fg="#ffffff",font=("arial",14),pady=10)
# password_label=tk.Label(frame,text="password",bg="#008080",fg="#ffffff",font=("arial",14),pady=2)
# username_entry=tk.Entry(frame,font=("arial",14))
# passward_entry=tk.Entry(frame,show="*",font=("arial",14))
# login_button=tk.Button(frame,text="Login",bg="#008080",fg="#ffffff",font=("arial",14))
# cancel_button=tk.Button(frame,text="Cancel",bg="#008080",fg="#ffffff",font=("arial",14))
# login_label.grid(row=0,column=0,columnspan=10)
# username_label.grid(row=1,column=0,pady=2)
# password_label.grid(row=2,column=0,pady=2)
# username_entry.grid(row=1,column=1)
# passward_entry.grid(row=2,column=1)
# login_button.grid(row=3,column=1)
# cancel_button.grid(row=3,column=2)
# frame.pack()
# top.mainloop()






#example design
import sqlite3
con=sqlite3.connect("it.db")
cursor=con.cursor()
cursor.execute("create table student(firstname text NOT NULL,secondname text NOT NULL, id text primary key NOT NULL,department text NOT NULL,year  integer NOT NULL,username text NOT NULL,password text NOT NULL)")
con.commit()
con.close()
import tkinter as tk
top=tk.Tk()
top.title("python")
top.geometry("400x600")
top.configure(bg="#008080")
frame=tk.Frame(bg="#008080")
registration_label=tk.Label(frame,text="Registration",bg="#008080",fg="#ffffff",font=("arial",30),pady=10)
firstname_label=tk.Label(frame,text="First Name",bg="#008080",fg="#ffffff",font=("arial",14),pady=2)
secondname_label=tk.Label(frame,text="Second Name",bg="#008080",fg="#ffffff",font=("arial",14),pady=2)
id_label=tk.Label(frame,text="ID No.",bg="#008080",fg="#ffffff",font=("arial",14),pady=2)
department_label=tk.Label(frame,text="Department",bg="#008080",fg="#ffffff",font=("arial",14),pady=2)
year_label=tk.Label(frame,text="Year",bg="#008080",fg="#ffffff",font=("arial",14),pady=2)
username_label=tk.Label(frame,text="User Name",bg="#008080",fg="#ffffff",font=("arial",14),pady=2)
password_label=tk.Label(frame,text="Password",bg="#008080",fg="#ffffff",font=("arial",14),pady=2)
firstname_entry=tk.Entry(frame,font=("arial",14))
secondname_entry=tk.Entry(frame,font=("arial",14))
id_entry=tk.Entry(frame,font=("arial",14))
department_entry=tk.Entry(frame,font=("arial",14))
year_entry=tk.Entry(frame,font=("arial",14))
username_entry=tk.Entry(frame,font=("arial",14))
password_entry=tk.Entry(frame,show="*",font=("arial",14))
insert_button=tk.Button(frame,text="Insert",bg="white",fg="pink",font=("arial",14))
retrive_button=tk.Button(frame,text="Retrive",bg="white",fg="pink",font=("arial",14))
search_button=tk.Button(frame,text="Search",bg="white",fg="pink",font=("arial",14))
update_button=tk.Button(frame,text="Update",bg="white",fg="pink",font=("arial",14))
delete_button=tk.Button(frame,text="Delete",bg="white",fg="pink",font=("arial",14))
clear_button=tk.Button(frame,text="Clear",bg="white",fg="pink",font=("arial",14))
#cancel_button=tk.Button(frame,text="Cancel",bg="#008080",fg="#ffffff",font=("arial",14))
registration_label.grid(row=0,column=0,columnspan=10)
firstname_label.grid(row=1,column=0,pady=5)
secondname_label.grid(row=2,column=0,pady=5)
id_label.grid(row=3,column=0,pady=5)
department_label.grid(row=4,column=0,pady=5)
year_label.grid(row=5,column=0,pady=5)
username_label.grid(row=6,column=0,pady=5)
password_label.grid(row=7,column=0,pady=5)
firstname_entry.grid(row=1,column=1)
secondname_entry.grid(row=2,column=1)
id_entry.grid(row=3,column=1)
department_entry.grid(row=4,column=1)
year_entry.grid(row=5,column=1)
username_entry.grid(row=6,column=1)
password_entry.grid(row=7,column=1)
insert_button.grid(row=8,column=2,padx=5)
retrive_button.grid(row=8,column=3,padx=5)
search_button.grid(row=8,column=4,padx=5)
update_button.grid(row=8,column=5,padx=5)
delete_button.grid(row=8,column=6,padx=5)
clear_button.grid(row=8,column=7,padx=5)
frame.pack()
top.mainloop()
